// <auto-generated />
using System;
using LystFiskerPortalenWEB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LystFiskerPortalenWEB.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251125094451_idk")]
    partial class idk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LystFiskerPortalenWEB.Models.Lure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Lures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Blank",
                            Name = "Blank",
                            PostId = 1,
                            Type = "Blank",
                            Weight = 0.0
                        },
                        new
                        {
                            Id = 2,
                            Color = "Sølv/blå",
                            Name = "Möresilda",
                            PostId = 2,
                            Type = "Klassisk kystblink til havørred, hornfisk og andre rovfisk. Går lidt dybere og kaster langt.",
                            Weight = 7.0
                        },
                        new
                        {
                            Id = 3,
                            Color = "Sølv",
                            Name = "Abu Garcia Toby",
                            PostId = 3,
                            Type = "Universelt blink til både sø og kyst. Fisker godt efter gedde, havørred, laks og aborre.",
                            Weight = 7.0
                        },
                        new
                        {
                            Id = 4,
                            Color = "pearl/white",
                            Name = "Savage Gear Sandeel Surf Seeker",
                            PostId = 4,
                            Type = "Moderne long-cast kystblink. Perfekt til havørred, især i hårdt vejr og lange kasteafstande.",
                            Weight = 35.0
                        },
                        new
                        {
                            Id = 5,
                            Color = "kobber/orange",
                            Name = "Hansen Flash",
                            PostId = 5,
                            Type = "Kystblink med livlig gang. Godt til havørred på lavere vand.",
                            Weight = 15.0
                        },
                        new
                        {
                            Id = 6,
                            Color = "chartreuse",
                            Name = "Snaps",
                            PostId = 6,
                            Type = "Kæmpe favorit blandt danske kystfiskere. Særligt effektiv på havørred og hornfisk.",
                            Weight = 25.0
                        },
                        new
                        {
                            Id = 7,
                            Color = "sølv/black stripes",
                            Name = "Abu Garcia Atom",
                            PostId = 0,
                            Type = "Geddeblink nr. 1 i mange år. Bred, vuggende gang – perfekt i søer og brakvand.",
                            Weight = 40.0
                        },
                        new
                        {
                            Id = 8,
                            Color = "Firetiger",
                            Name = "Blue Fox Lucius",
                            PostId = 0,
                            Type = "Geddeblink til både lavt og dybt vand. God til at provokere hug i uklart vand.",
                            Weight = 27.0
                        },
                        new
                        {
                            Id = 9,
                            Color = "rød/sølv",
                            Name = "Solvkroken Stingsilda",
                            PostId = 0,
                            Type = "Kraftigt, tungt blink til havfiskeri og kyst. Bruges ofte til torsk, makrel og havørred.",
                            Weight = 18.0
                        },
                        new
                        {
                            Id = 10,
                            Color = "sølv/blue stripes",
                            Name = "Mepps Syclops",
                            PostId = 0,
                            Type = "Allround blink med meget “flappende” gang. Bruges til både aborre, gedde og laks.",
                            Weight = 12.0
                        },
                        new
                        {
                            Id = 11,
                            Color = "Pink Panther",
                            Name = "Westin D360",
                            PostId = 0,
                            Type = "Slankt long-distance blink – super til havørred, især i klart vand.",
                            Weight = 22.0
                        });
                });

            modelBuilder.Entity("LystFiskerPortalenWEB.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Likes")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LureId")
                        .HasColumnType("int");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("TechniqueId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LureId");

                    b.HasIndex("ProfileID");

                    b.HasIndex("TechniqueId");

                    b.ToTable("Posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "En fantastisk dag ved søen med masser af fisk!",
                            Likes = 10,
                            Location = "Søen ved Skoven",
                            LureId = 1,
                            Picture = "public/TestPictures/TestFisk1.png",
                            ProfileID = "testid",
                            TechniqueId = 1,
                            Title = "Fisketur ved søen"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "En spændende dag på havet med store fangster.",
                            Likes = 4,
                            Location = "Kysten ved Byen",
                            LureId = 2,
                            Picture = "public/TestPictures/TestFisk2.jpg",
                            ProfileID = "testid",
                            TechniqueId = 2,
                            Title = "Havfiskeri eventyr"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Jeg fangede en kæmpe blæksprutte - det ikke AI",
                            Likes = 2,
                            Location = "Byens kyst",
                            LureId = 3,
                            Picture = "public/TestPictures/TestFisk3.png",
                            ProfileID = "testid",
                            TechniqueId = 3,
                            Title = "Kæmpe blæksprutte fanget!"
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Søger single lystfiskere i Odense beliggenhed",
                            Likes = 0,
                            LureId = 4,
                            ProfileID = "testid",
                            TechniqueId = 4,
                            Title = "Hej Fiskere!"
                        });
                });

            modelBuilder.Entity("LystFiskerPortalenWEB.Models.Profile", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "testid",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3c33c21b-c6da-4341-b80f-1d469a133df3",
                            EmailConfirmed = false,
                            ImagePath = "/public/Images/DefaultProfileImage.png",
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            Role = "user",
                            SecurityStamp = "2db6ec6c-351c-4c00-a356-320fd4abb557",
                            TwoFactorEnabled = false,
                            UserName = "testuser"
                        });
                });

            modelBuilder.Entity("LystFiskerPortalenWEB.Models.Technique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Techniques", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Blank",
                            Name = "Blank",
                            PostId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "En af de mest klassiske rigs i både salt- og ferskvand. Et lod sidder nederst, og 1–3 kroge sidder på korte forfang (”trembler”) over loddet.",
                            Name = "Paternoster-rig",
                            PostId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Et kuglelod glider frit på hovedlinen foran en perle og en svirvel. Herefter kommer et langt forfang med en enkeltkrog.",
                            Name = "Carolina-rig",
                            PostId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Ligner Carolina-rigget, men loddet sidder direkte foran agnen (typisk med en lille gummistopper). Agnen (ofte en softbait) kan rigges ”weedless”.",
                            Name = "Texas-rig",
                            PostId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Et lod trækkes frit på hovedlinen, enten gennem et rør eller et glidelod, før en svirvel og et forfang.",
                            Name = "Glidende bundrig",
                            PostId = 0
                        },
                        new
                        {
                            Id = 6,
                            Description = "En aflange kasteflåd (bombarda) monteres på linen, så man kan kaste selv små fluer eller lette agn meget langt.",
                            Name = "Bombarda-rig",
                            PostId = 0
                        },
                        new
                        {
                            Id = 7,
                            Description = "En enkeltkrog bindes på linen, og loddet sidder i enden. Krogen kan justeres i præcis den ønskede højde.",
                            Name = "Drop-shot-rig",
                            PostId = 0
                        },
                        new
                        {
                            Id = 8,
                            Description = "Krogen bindes på en speciel måde, hvor agnen (fx boilies) sidder på en lille “hair” efter krogen og ikke direkte på krogen.",
                            Name = "Hair-rig",
                            PostId = 0
                        },
                        new
                        {
                            Id = 9,
                            Description = "Et simpelt rig med flåd, stopperknuder, lodder og krog.",
                            Name = "Float-rig",
                            PostId = 0
                        },
                        new
                        {
                            Id = 10,
                            Description = "Bruges især til dødagn, hvor et spinnerblad eller rotator tilføjes for at give en livlig gang.",
                            Name = "Spinner-rig",
                            PostId = 0
                        },
                        new
                        {
                            Id = 11,
                            Description = "Specialiseret bundrig med korte forfang og farvede perler/spinnerblade, ofte med to kroge.",
                            Name = "Fladfiskerig",
                            PostId = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LystFiskerPortalenWEB.Models.Post", b =>
                {
                    b.HasOne("LystFiskerPortalenWEB.Models.Lure", "Lure")
                        .WithMany("Post")
                        .HasForeignKey("LureId");

                    b.HasOne("LystFiskerPortalenWEB.Models.Profile", "Profile")
                        .WithMany("Posts")
                        .HasForeignKey("ProfileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LystFiskerPortalenWEB.Models.Technique", "Technique")
                        .WithMany("Post")
                        .HasForeignKey("TechniqueId");

                    b.Navigation("Lure");

                    b.Navigation("Profile");

                    b.Navigation("Technique");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LystFiskerPortalenWEB.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LystFiskerPortalenWEB.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LystFiskerPortalenWEB.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LystFiskerPortalenWEB.Models.Profile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LystFiskerPortalenWEB.Models.Lure", b =>
                {
                    b.Navigation("Post");
                });

            modelBuilder.Entity("LystFiskerPortalenWEB.Models.Profile", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("LystFiskerPortalenWEB.Models.Technique", b =>
                {
                    b.Navigation("Post");
                });
#pragma warning restore 612, 618
        }
    }
}
